# Generated by Django 5.2.7 on 2025-12-21 13:16

import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIGenerationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "model_used",
                    models.CharField(max_length=100, verbose_name="AI model used"),
                ),
                ("topic", models.CharField(max_length=255, verbose_name="topic")),
                (
                    "question_count",
                    models.PositiveIntegerField(verbose_name="questions generated"),
                ),
                ("success", models.BooleanField(default=True, verbose_name="success")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="generated at"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Generation Log",
                "verbose_name_plural": "AI Generation Logs",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="rule name")),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="rule key"
                    ),
                ),
                ("value", models.JSONField(default=dict, verbose_name="rule value")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("exam", "Exams"),
                            ("assignment", "Assignments"),
                            ("grading", "Grading"),
                            ("attendance", "Attendance"),
                        ],
                        default="all",
                        max_length=50,
                        verbose_name="applies to",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Rule",
                "verbose_name_plural": "Assessment Rules",
                "ordering": ["applies_to", "name"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="assignment title"),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("homework", "Homework"),
                            ("classwork", "Classwork"),
                            ("project", "Project"),
                            ("research", "Research Paper"),
                            ("presentation", "Presentation"),
                            ("quiz", "Quiz"),
                            ("exam", "Exam"),
                            ("lab_report", "Lab Report"),
                            ("essay", "Essay"),
                            ("group_project", "Group Project"),
                        ],
                        default="homework",
                        max_length=20,
                        verbose_name="assignment type",
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="instructions"),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="publish date"
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="due date")),
                (
                    "assigned_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="assigned date"
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="total marks",
                    ),
                ),
                (
                    "passing_marks",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="passing marks",
                    ),
                ),
                (
                    "weightage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Weightage in percentage for final grade",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="weightage in final grade",
                    ),
                ),
                (
                    "grading_criteria",
                    models.TextField(blank=True, verbose_name="grading criteria"),
                ),
                (
                    "allow_late_submissions",
                    models.BooleanField(
                        default=True, verbose_name="allow late submissions"
                    ),
                ),
                (
                    "late_submission_penalty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="late submission penalty percentage",
                    ),
                ),
                (
                    "max_submission_attempts",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="maximum submission attempts",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assignments/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "ppt",
                                    "pptx",
                                    "txt",
                                    "zip",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ]
                            )
                        ],
                        verbose_name="attachment",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="file size in bytes"
                    ),
                ),
                (
                    "max_file_size",
                    models.PositiveIntegerField(
                        default=10485760,
                        verbose_name="maximum file size for submissions",
                    ),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="tags"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="is published"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="submission date"
                    ),
                ),
                (
                    "submission_text",
                    models.TextField(blank=True, verbose_name="submission text"),
                ),
                (
                    "submitted_content",
                    models.TextField(blank=True, verbose_name="submitted content"),
                ),
                (
                    "submission_attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assignment_submissions/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "ppt",
                                    "pptx",
                                    "txt",
                                    "zip",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "mp4",
                                    "mp3",
                                ]
                            )
                        ],
                        verbose_name="submission attachment",
                    ),
                ),
                (
                    "submission_file_size",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="submission file size in bytes",
                    ),
                ),
                (
                    "submission_file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="original file name"
                    ),
                ),
                (
                    "submission_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("late", "Late"),
                            ("under_review", "Under Review"),
                            ("graded", "Graded"),
                            ("returned", "Returned"),
                            ("resubmitted", "Resubmitted"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="submission status",
                    ),
                ),
                (
                    "submission_attempt",
                    models.PositiveIntegerField(
                        default=1, verbose_name="submission attempt"
                    ),
                ),
                (
                    "is_late_submission",
                    models.BooleanField(
                        default=False, verbose_name="is late submission"
                    ),
                ),
                (
                    "late_minutes",
                    models.PositiveIntegerField(default=0, verbose_name="minutes late"),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="marks obtained",
                    ),
                ),
                (
                    "penalty_applied",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="penalty applied",
                    ),
                ),
                (
                    "final_marks",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="final marks after penalty",
                    ),
                ),
                (
                    "rubric_scores",
                    models.JSONField(
                        blank=True, null=True, verbose_name="rubric scores"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="teacher feedback"),
                ),
                (
                    "student_feedback",
                    models.TextField(blank=True, verbose_name="student feedback"),
                ),
                (
                    "graded_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="graded date"
                    ),
                ),
                (
                    "feedback_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="feedback date"
                    ),
                ),
                (
                    "is_feedback_read",
                    models.BooleanField(
                        default=False, verbose_name="is feedback read by student"
                    ),
                ),
                (
                    "feedback_read_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="feedback read date"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "ordering": ["display_order", "-due_date", "subject"],
            },
        ),
        migrations.CreateModel(
            name="CourseGrade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "assignments",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="assignments score",
                    ),
                ),
                (
                    "mid_exam",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="mid-term exam",
                    ),
                ),
                (
                    "quizzes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="quizzes score",
                    ),
                ),
                (
                    "attendance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="attendance percentage",
                    ),
                ),
                (
                    "final_exam",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="final exam",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        editable=False,
                        max_digits=5,
                        verbose_name="total score",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, editable=False, max_length=2, verbose_name="grade"
                    ),
                ),
                (
                    "grade_point",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        editable=False,
                        max_digits=3,
                        verbose_name="grade point",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, editable=False, max_length=20, verbose_name="remark"
                    ),
                ),
                (
                    "credit_hours",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Credit hours for this course",
                        verbose_name="credit hours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Grade",
                "verbose_name_plural": "Course Grades",
                "ordering": ["student", "subject"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="exam name")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="exam code"
                    ),
                ),
                ("exam_date", models.DateField(verbose_name="exam date")),
                ("start_time", models.TimeField(verbose_name="start time")),
                ("end_time", models.TimeField(verbose_name="end time")),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="total marks",
                    ),
                ),
                (
                    "passing_marks",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="passing marks",
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="exam venue"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="instructions"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="is published"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
                "ordering": ["exam_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ExamAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "is_present",
                    models.BooleanField(default=True, verbose_name="is present"),
                ),
                (
                    "late_minutes",
                    models.PositiveIntegerField(default=0, verbose_name="late minutes"),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="remarks")),
            ],
            options={
                "verbose_name": "Exam Attendance",
                "verbose_name_plural": "Exam Attendance",
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="marks for this question",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="question order"
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override question time limit for this exam",
                        null=True,
                        verbose_name="time limit in seconds",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Question",
                "verbose_name_plural": "Exam Questions",
                "ordering": ["exam", "order"],
            },
        ),
        migrations.CreateModel(
            name="ExamType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="exam type name"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="exam type code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "weightage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weightage in percentage for final grade calculation",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="weightage",
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(default=False, verbose_name="is final exam"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Type",
                "verbose_name_plural": "Exam Types",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("grade", models.CharField(max_length=10, verbose_name="grade")),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="description"),
                ),
                (
                    "min_mark",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="minimum marks",
                    ),
                ),
                (
                    "max_mark",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="maximum marks",
                    ),
                ),
                (
                    "grade_point",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4.0),
                        ],
                        verbose_name="grade point",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=100, verbose_name="remark"),
                ),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "ordering": ["grading_system", "min_mark"],
            },
        ),
        migrations.CreateModel(
            name="GradingSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="grading system name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="grading system code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "Grading System",
                "verbose_name_plural": "Grading Systems",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Mark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="marks obtained",
                    ),
                ),
                (
                    "max_marks",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=6,
                        verbose_name="maximum marks",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="percentage",
                    ),
                ),
                (
                    "is_absent",
                    models.BooleanField(default=False, verbose_name="is absent"),
                ),
                (
                    "grace_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="grace marks",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="remarks")),
                (
                    "entered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="entered at"),
                ),
            ],
            options={
                "verbose_name": "Mark",
                "verbose_name_plural": "Marks",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                        verbose_name="question type",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="question text")),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="explanation/answer key"),
                ),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="marks",
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time limit for answering this question",
                        null=True,
                        verbose_name="time limit in seconds",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="difficulty level",
                    ),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="tags"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["question_bank", "difficulty_level", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="question bank name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="topic/chapter"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="difficulty level",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "bank_type",
                    models.CharField(
                        choices=[("question_bank", "Question Bank"), ("quiz", "Quiz")],
                        default="question_bank",
                        help_text="Whether this is a question bank or a complete quiz",
                        max_length=20,
                        verbose_name="bank type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("assignment", "Assignment"),
                            ("exam", "Exam"),
                            ("practice", "Practice Quiz"),
                        ],
                        help_text="Category for quiz-type question banks",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "random_order",
                    models.BooleanField(
                        default=False,
                        help_text="Display questions in random order",
                        verbose_name="random order",
                    ),
                ),
                (
                    "answers_at_end",
                    models.BooleanField(
                        default=False,
                        help_text="Show answers at the end instead of after each question",
                        verbose_name="answers at end",
                    ),
                ),
                (
                    "exam_paper",
                    models.BooleanField(
                        default=False,
                        help_text="Store results for manual grading",
                        verbose_name="exam paper",
                    ),
                ),
                (
                    "single_attempt",
                    models.BooleanField(
                        default=False,
                        help_text="Allow only one attempt per student",
                        verbose_name="single attempt",
                    ),
                ),
                (
                    "pass_mark",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Percentage required to pass",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="pass mark",
                    ),
                ),
                (
                    "draft",
                    models.BooleanField(
                        default=False,
                        help_text="Draft quizzes are not visible to students",
                        verbose_name="draft",
                    ),
                ),
                (
                    "url",
                    models.SlugField(
                        blank=True, help_text="URL slug for the quiz", unique=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modified timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Bank",
                "verbose_name_plural": "Question Banks",
                "ordering": ["subject", "topic", "difficulty_level"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("option_text", models.TextField(verbose_name="option text")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="is correct"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Option",
                "verbose_name_plural": "Question Options",
                "ordering": ["question", "order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "question_order",
                    models.TextField(
                        help_text="Comma-separated list of question IDs in order",
                        verbose_name="question order",
                    ),
                ),
                (
                    "question_list",
                    models.TextField(
                        help_text="Current questions remaining to answer",
                        verbose_name="question list",
                    ),
                ),
                (
                    "user_answers",
                    models.TextField(
                        blank=True,
                        default="{}",
                        help_text="JSON string storing answers by question ID",
                        verbose_name="user answers",
                    ),
                ),
                (
                    "incorrect_questions",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of incorrectly answered question IDs",
                        verbose_name="incorrect questions",
                    ),
                ),
                (
                    "current_score",
                    models.IntegerField(default=0, verbose_name="current score"),
                ),
                (
                    "complete",
                    models.BooleanField(default=False, verbose_name="complete"),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="start time"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="end time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Attempt",
                "verbose_name_plural": "Quiz Attempts",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="QuizProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "score",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated quiz scores in format: quiz_id,correct,total,",
                        verbose_name="score data",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Progress",
                "verbose_name_plural": "Quiz Progress Records",
            },
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="generated at"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="is approved"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approved at"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="comments")),
                (
                    "parent_signature",
                    models.BooleanField(
                        default=False, verbose_name="parent signature received"
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Card",
                "verbose_name_plural": "Report Cards",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="total marks",
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="marks obtained",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="percentage",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="rank"
                    ),
                ),
                (
                    "total_students",
                    models.PositiveIntegerField(verbose_name="total students"),
                ),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Attendance percentage for the period",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="attendance percentage",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="remarks")),
                (
                    "is_promoted",
                    models.BooleanField(default=False, verbose_name="is promoted"),
                ),
            ],
            options={
                "verbose_name": "Result",
                "verbose_name_plural": "Results",
            },
        ),
        migrations.CreateModel(
            name="ResultSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="marks obtained",
                    ),
                ),
                (
                    "max_marks",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="maximum marks",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="percentage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Result Subject",
                "verbose_name_plural": "Result Subjects",
                "ordering": ["subject__name"],
            },
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(blank=True, verbose_name="answer text"),
                ),
                (
                    "selected_options",
                    models.JSONField(
                        blank=True,
                        help_text="List of selected option IDs for multiple choice",
                        null=True,
                        verbose_name="selected options",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="is correct"
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="marks obtained",
                    ),
                ),
                (
                    "time_taken",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="time taken in seconds"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "is_graded",
                    models.BooleanField(default=False, verbose_name="is graded"),
                ),
            ],
            options={
                "verbose_name": "Student Answer",
                "verbose_name_plural": "Student Answers",
                "ordering": ["exam_question__order", "submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TakenCourse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "assignment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="assignment score",
                    ),
                ),
                (
                    "mid_exam",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="mid-term exam",
                    ),
                ),
                (
                    "quiz",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="quiz score",
                    ),
                ),
                (
                    "attendance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="attendance percentage",
                    ),
                ),
                (
                    "final_exam",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="final exam",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=5,
                        verbose_name="total score",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, editable=False, max_length=2, verbose_name="grade"
                    ),
                ),
                (
                    "point",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=4,
                        verbose_name="grade point",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        verbose_name="comment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taken Course",
                "verbose_name_plural": "Taken Courses",
                "ordering": ["student", "course"],
            },
        ),
    ]
