# Generated by Django 5.2.7 on 2026-02-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
        ('assessment', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'academic_class', 'exam_type', 'institution')},
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['student', 'institution'], name='assessment__student_17cfd7_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['academic_class', 'institution'], name='assessment__academi_87a560_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['is_approved', 'institution'], name='assessment__is_appr_5aaa1b_idx'),
        ),
    ]
