# Generated by Django 5.2.7 on 2025-12-16 15:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_remove_session_requirement_from_enrollment"),
        ("assessment", "0002_initial"),
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="answers_at_end",
            field=models.BooleanField(
                default=False,
                help_text="Show answers only after quiz completion",
                verbose_name="answers at end",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="bank_type",
            field=models.CharField(
                choices=[
                    ("quiz", "Quiz"),
                    ("exam", "Exam"),
                    ("assignment", "Assignment"),
                    ("practice", "Practice"),
                ],
                default="quiz",
                help_text="Type of assessment this question bank is for",
                max_length=20,
                verbose_name="question bank type",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="pass_mark",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Percentage required to pass",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="pass mark",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="random_order",
            field=models.BooleanField(
                default=False,
                help_text="Display questions in random order when used",
                verbose_name="random order",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="single_attempt",
            field=models.BooleanField(
                default=False,
                help_text="Allow only one attempt per student",
                verbose_name="single attempt",
            ),
        ),
        migrations.CreateModel(
            name="AIGenerationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "model_used",
                    models.CharField(max_length=100, verbose_name="AI model used"),
                ),
                ("topic", models.CharField(max_length=255, verbose_name="topic")),
                (
                    "question_count",
                    models.PositiveIntegerField(verbose_name="questions generated"),
                ),
                ("success", models.BooleanField(default=True, verbose_name="success")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="generated at"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "question_bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_generations",
                        to="assessment.questionbank",
                        verbose_name="question bank",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generations",
                        to="academics.teacher",
                        verbose_name="teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Generation Log",
                "verbose_name_plural": "AI Generation Logs",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "question_order",
                    models.TextField(
                        help_text="Comma-separated list of question IDs in order",
                        verbose_name="question order",
                    ),
                ),
                (
                    "question_list",
                    models.TextField(
                        help_text="Current questions remaining to answer",
                        verbose_name="question list",
                    ),
                ),
                (
                    "user_answers",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object storing answers by question ID",
                        verbose_name="user answers",
                    ),
                ),
                (
                    "incorrect_questions",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of incorrectly answered question IDs",
                        verbose_name="incorrect questions",
                    ),
                ),
                (
                    "current_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="current score"
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(default=0, verbose_name="max score"),
                ),
                (
                    "complete",
                    models.BooleanField(default=False, verbose_name="complete"),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="start time"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="end time"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "question_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assessment.questionbank",
                        verbose_name="question bank",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="academics.student",
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Attempt",
                "verbose_name_plural": "Quiz Attempts",
                "ordering": ["-start_time"],
                "unique_together": {("student", "question_bank")},
            },
        ),
    ]
