# Generated by Django 5.2.7 on 2025-12-16 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0004_questionbank_draft_quizprogress_coursegrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assignment", "Assignment"),
                    ("exam", "Exam"),
                    ("practice", "Practice Quiz"),
                ],
                help_text="Category for quiz classification and progress tracking",
                max_length=20,
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="exam_paper",
            field=models.BooleanField(
                default=False,
                help_text="If yes, the result of each attempt by a user will be stored. Necessary for marking.",
                verbose_name="exam paper",
            ),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="answers_at_end",
            field=models.BooleanField(
                default=False,
                help_text="Correct answer is NOT shown after question. Answers displayed at the end.",
                verbose_name="answers at end",
            ),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="pass_mark",
            field=models.SmallIntegerField(
                default=50,
                help_text="Percentage required to pass exam.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="pass mark",
            ),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="single_attempt",
            field=models.BooleanField(
                default=False,
                help_text="If yes, only one attempt by a user will be permitted.",
                verbose_name="single attempt",
            ),
        ),
    ]
