# Generated by Django 5.2.7 on 2025-12-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0005_questionbank_category_questionbank_exam_paper_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="choice_order",
            field=models.CharField(
                blank=True,
                choices=[
                    ("content", "Content"),
                    ("random", "Random"),
                    ("none", "None"),
                ],
                help_text="The order in which multiple-choice options are displayed to the user",
                max_length=30,
                verbose_name="choice order",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="figure",
            field=models.ImageField(
                blank=True,
                help_text="Add an image for the question if necessary.",
                upload_to="questions/%Y/%m/%d",
                verbose_name="figure",
            ),
        ),
    ]
