# Generated by Django 5.2.7 on 2025-12-16 16:48

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_remove_session_requirement_from_enrollment"),
        ("assessment", "0006_question_choice_order_question_figure"),
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="choice_order",
        ),
        migrations.RemoveField(
            model_name="question",
            name="figure",
        ),
        migrations.RemoveField(
            model_name="questionbank",
            name="answers_at_end",
        ),
        migrations.RemoveField(
            model_name="questionbank",
            name="bank_type",
        ),
        migrations.RemoveField(
            model_name="questionbank",
            name="category",
        ),
        migrations.RemoveField(
            model_name="questionbank",
            name="draft",
        ),
        migrations.RemoveField(
            model_name="questionbank",
            name="exam_paper",
        ),
        migrations.RemoveField(
            model_name="questionbank",
            name="pass_mark",
        ),
        migrations.RemoveField(
            model_name="questionbank",
            name="random_order",
        ),
        migrations.RemoveField(
            model_name="questionbank",
            name="single_attempt",
        ),
        migrations.CreateModel(
            name="TakenCourse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "assignment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="assignment score",
                    ),
                ),
                (
                    "mid_exam",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="mid-term exam",
                    ),
                ),
                (
                    "quiz",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="quiz score",
                    ),
                ),
                (
                    "attendance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="attendance percentage",
                    ),
                ),
                (
                    "final_exam",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="final exam",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=5,
                        verbose_name="total score",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, editable=False, max_length=2, verbose_name="grade"
                    ),
                ),
                (
                    "point",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=4,
                        verbose_name="grade point",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        verbose_name="comment",
                    ),
                ),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taken_courses",
                        to="academics.academicsession",
                        verbose_name="academic session",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taken_courses",
                        to="academics.subject",
                        verbose_name="course",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taken_courses",
                        to="academics.student",
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taken Course",
                "verbose_name_plural": "Taken Courses",
                "ordering": ["student", "course"],
                "unique_together": {("student", "course", "academic_session")},
            },
        ),
    ]
