# Generated by Django 5.2.7 on 2025-12-16 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment",
            "0007_remove_question_choice_order_remove_question_figure_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="answers_at_end",
            field=models.BooleanField(
                default=False,
                help_text="Show answers at the end instead of after each question",
                verbose_name="answers at end",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="bank_type",
            field=models.CharField(
                choices=[("question_bank", "Question Bank"), ("quiz", "Quiz")],
                default="question_bank",
                help_text="Whether this is a question bank or a complete quiz",
                max_length=20,
                verbose_name="bank type",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assignment", "Assignment"),
                    ("exam", "Exam"),
                    ("practice", "Practice Quiz"),
                ],
                help_text="Category for quiz-type question banks",
                max_length=20,
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="draft",
            field=models.BooleanField(
                default=False,
                help_text="Draft quizzes are not visible to students",
                verbose_name="draft",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="exam_paper",
            field=models.BooleanField(
                default=False,
                help_text="Store results for manual grading",
                verbose_name="exam paper",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="pass_mark",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Percentage required to pass",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="pass mark",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="random_order",
            field=models.BooleanField(
                default=False,
                help_text="Display questions in random order",
                verbose_name="random order",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="single_attempt",
            field=models.BooleanField(
                default=False,
                help_text="Allow only one attempt per student",
                verbose_name="single attempt",
            ),
        ),
    ]
