# Generated by Django 5.2.7 on 2025-12-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment",
            "0008_questionbank_answers_at_end_questionbank_bank_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizattempt",
            name="max_score",
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="current_score",
            field=models.IntegerField(default=0, verbose_name="current score"),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="user_answers",
            field=models.TextField(
                blank=True,
                default="{}",
                help_text="JSON string storing answers by question ID",
                verbose_name="user answers",
            ),
        ),
    ]
