# Generated by Django 5.2.7 on 2025-12-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0009_remove_quizattempt_max_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="timestamp",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modified timestamp"
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="url",
            field=models.SlugField(
                blank=True, help_text="URL slug for the quiz", unique=True
            ),
        ),
    ]
