# Generated by Django 5.2.7 on 2025-12-27 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gradelevel",
            name="institution",
        ),
    ]
