# Generated by Django 5.2.7 on 2025-12-16 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="academic_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
    ]
