# Generated by Django 5.2.7 on 2025-12-17 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_remove_session_requirement_from_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department for tertiary education enrollments",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="academics.department",
                verbose_name="department",
            ),
        ),
    ]
