# Generated by Django 5.2.7 on 2025-12-17 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_enrollment_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary department for tertiary education students",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.department",
                verbose_name="department",
            ),
        ),
    ]
