# Generated by Django 4.2.25 on 2025-12-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groqquizsession",
            name="config",
        ),
        migrations.RemoveField(
            model_name="groqquizsession",
            name="course",
        ),
        migrations.RemoveField(
            model_name="groqquizsession",
            name="user",
        ),
        migrations.DeleteModel(
            name="GroqQuizConfig",
        ),
        migrations.DeleteModel(
            name="GroqQuizSession",
        ),
    ]
