"""Alter SequenceGenerator uniqueness to be per-institution and normalize prefixes.

Generated by assistant.
"""

from django.db import migrations, models


def normalize_prefixes(apps, schema_editor):
    SequenceGenerator = apps.get_model("core", "SequenceGenerator")
    Institution = apps.get_model("core", "Institution")

    for sg in SequenceGenerator.objects.select_related("institution").all():
        inst = sg.institution
        if not inst:
            continue

        if sg.sequence_type == "student_id":
            desired = f"{inst.code}-STU-"
            if not (sg.prefix or "").startswith(desired):
                sg.prefix = desired
                sg.save(update_fields=["prefix"])

        if sg.sequence_type == "employee_id":
            desired = f"{inst.code}-EMP-"
            if not (sg.prefix or "").startswith(desired):
                sg.prefix = desired
                sg.save(update_fields=["prefix"])


def noop_reverse(apps, schema_editor):
    # Intentionally left blank — reversing data normalization is not attempted.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_systemconfig_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequencegenerator",
            name="sequence_type",
            field=models.CharField(
                max_length=50,
                choices=[
                    ("student_id", "Student ID"),
                    ("employee_id", "Employee ID"),
                    ("invoice", "Invoice Number"),
                    ("receipt", "Receipt Number"),
                    ("library_book", "Library Book ID"),
                    ("transport_bus", "Transport Bus ID"),
                    ("staff_application", "Staff Application Number"),
                ],
                verbose_name="sequence type",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sequencegenerator",
            unique_together={("sequence_type", "institution")},
        ),
        migrations.RunPython(normalize_prefixes, noop_reverse),
    ]
