# Generated by Django 5.2.7 on 2025-12-27 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_systemconfig_institution"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginhistory",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Institution this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_history_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
    ]
