# Generated by Django 5.2.7 on 2025-12-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_loginhistory_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("auto", "Auto (System)"),
                ],
                default="light",
                help_text="Choose your preferred theme or set to auto to follow system preference",
                max_length=20,
                verbose_name="theme preference",
            ),
        ),
    ]
