# Generated by Django 5.2.7 on 2025-12-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_staffapplication_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentapplication",
            name="grade_applying_for",
            field=models.CharField(max_length=100, verbose_name="grade applying for"),
        ),
    ]
