# Generated by Django 5.2.7 on 2025-12-17 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_enrollment_department"),
        ("users", "0003_alter_studentapplication_grade_applying_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department for tertiary education applications",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_applications",
                to="academics.department",
                verbose_name="department",
            ),
        ),
    ]
