# Generated by Django 5.2.7 on 2025-12-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_role_role_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Administrator"),
                    ("school_admin", "School Administrator"),
                    ("admin", "Administrator"),
                    ("principal", "Principal"),
                    ("department_head", "Department Head"),
                    ("counselor", "School Counselor"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                    ("accountant", "Accountant"),
                    ("librarian", "Librarian"),
                    ("activities_coordinator", "Activities Coordinator"),
                    ("driver", "Driver"),
                    ("support", "Support Staff"),
                    ("transport_manager", "Transport Manager"),
                    ("hostel_warden", "Hostel Warden"),
                ],
                max_length=25,
                unique=True,
                verbose_name="role type",
            ),
        ),
    ]
