# Generated by Django 5.2.7 on 2025-12-27 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="legaldocument",
            name="institution",
        ),
    ]
