# Generated by Django 5.2.7 on 2025-12-27 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_initial"),
        ("core", "0003_remove_systemconfig_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Institution this audit log belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
    ]
