# Generated by Django 5.2.7 on 2025-12-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kpi",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="reporttype",
            name="institution",
        ),
    ]
